name: Ruby

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    services:
      redis:
        image: redis
        ports:
          - '6379:6379'
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [3.1, "3.0", 2.7, 2.6, jruby]
        gemfile:
          [
            Gemfile,
            gemfiles/rails_5.2.x.gemfile,
            gemfiles/rails_6.0.x.gemfile,
            gemfiles/rails_7.0.x.gemfile,
          ]
        exclude:
          # Ruby 3.1 is not supported by Rails 5.2.x
          - ruby_version: 3.1
            gemfile: gemfiles/rails_5.2.x.gemfile,

          # Ruby 3.x is not supported by Rails 5.2.x
          - ruby_version: 3.0
            gemfile: gemfiles/rails_5.2.x.gemfile,

          # Ruby 2.6.x is not supported by Rails 7.0.x
          - ruby_version: 2.6
            gemfile: gemfiles/rails_7.0.x.gemfile

          # Ruby 2.6.x is not supported by this Gemfile
          - ruby_version: 2.6
            gemfile: Gemfile

          # JRuby is not supported by Rails 7.0.x
          - ruby_version: jruby
            gemfile: gemfiles/rails_7.0.x.gemfile

          # JRuby is not supported by this Gemfile
          - ruby_version: jruby
            gemfile: Gemfile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true # 'bundle install' and cache
      - name: Build and test with Rake
        run: bundle exec rake
